// Mock data for Mantra platform

export const MOCK_USERS = [
  {
    id: "u1",
    name: "Dr. Amara Osei",
    username: "amara.osei",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=amara&backgroundColor=fef9f2",
    university: "University of Lagos",
    department: "Computer Science",
    level: "PhD Candidate",
    bio: "Researching distributed systems and collaborative learning platforms. Building the future of academic knowledge sharing.",
    followers: 2841,
    following: 312,
    repositories: 18,
    contributions: 4723,
    stars: 891,
    joinedAt: "2023-01-15",
    achievements: ["top-contributor", "verified-educator", "100-commits"],
  },
  {
    id: "u2",
    name: "Marcus Chen",
    username: "marcus.chen",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=marcus&backgroundColor=fedb99",
    university: "MIT",
    department: "Physics",
    level: "Professor",
    bio: "Teaching quantum mechanics and computational physics. Open source science advocate.",
    followers: 5120,
    following: 89,
    repositories: 34,
    contributions: 9812,
    stars: 2341,
    joinedAt: "2022-08-22",
    achievements: ["verified-educator", "hall-of-fame", "top-professor"],
  },
  {
    id: "u3",
    name: "Sofia Reyes",
    username: "sofia.reyes",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sofia&backgroundColor=f2dfd1",
    university: "Universidad Nacional",
    department: "Mathematics",
    level: "Lecturer",
    bio: "Pure mathematics enthusiast. Creating beautiful, accessible learning materials for abstract algebra.",
    followers: 1203,
    following: 445,
    repositories: 12,
    contributions: 2198,
    stars: 567,
    joinedAt: "2023-06-10",
    achievements: ["rising-star", "verified-educator"],
  },
  {
    id: "u4",
    name: "James Okafor",
    username: "james.okafor",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=james&backgroundColor=e3c282",
    university: "University of Cambridge",
    department: "Biology",
    level: "Research Fellow",
    bio: "Molecular biology and genomics. Making CRISPR and gene editing accessible to everyone.",
    followers: 892,
    following: 203,
    repositories: 9,
    contributions: 1456,
    stars: 334,
    joinedAt: "2024-01-03",
    achievements: ["rising-star"],
  },
];

export const MOCK_REPOSITORIES = [
  {
    id: "r1",
    title: "Advanced Quantum Mechanics",
    slug: "advanced-quantum-mechanics",
    description: "A comprehensive repository for QM covering wave functions, operators, perturbation theory, and path integrals. Includes solved problem sets from MIT 8.321.",
    courseCode: "PHYS 8.321",
    university: "MIT",
    department: "Physics",
    semester: "Spring 2025",
    owner: MOCK_USERS[1],
    contributors: [MOCK_USERS[0], MOCK_USERS[2]],
    tags: ["quantum", "physics", "wave-mechanics", "advanced"],
    stars: 1847,
    forks: 342,
    discussions: 89,
    views: 24500,
    lastUpdated: "2025-05-20",
    isPublic: true,
    isVerified: true,
    readme: "# Advanced Quantum Mechanics\n\nWelcome to the QM learning hub...",
    modules: [
      { id: "m1", title: "Wave Functions & Hilbert Space", type: "lecture", files: 12, duration: "3h 20m" },
      { id: "m2", title: "Operators and Observables", type: "lecture", files: 8, duration: "2h 10m" },
      { id: "m3", title: "Perturbation Theory", type: "lecture", files: 15, duration: "4h 45m" },
      { id: "m4", title: "Problem Sets (Solved)", type: "assignment", files: 24, duration: null },
    ],
    coverGradient: "from-primary-container to-primary",
    updatedDaysAgo: 5,
    language: "PDF",
  },
  {
    id: "r2",
    title: "Data Structures & Algorithms",
    slug: "data-structures-algorithms",
    description: "Complete DSA curriculum with implementations in Python and Java. Over 200 annotated solutions, complexity analysis, and visual diagrams.",
    courseCode: "CS 101",
    university: "University of Lagos",
    department: "Computer Science",
    semester: "Fall 2024",
    owner: MOCK_USERS[0],
    contributors: [MOCK_USERS[3], MOCK_USERS[1]],
    tags: ["algorithms", "python", "java", "computer-science"],
    stars: 2312,
    forks: 891,
    discussions: 203,
    views: 52000,
    lastUpdated: "2025-05-22",
    isPublic: true,
    isVerified: true,
    readme: "# Data Structures & Algorithms\n\nThe definitive DSA resource...",
    modules: [
      { id: "m5", title: "Arrays & Linked Lists", type: "lecture", files: 10, duration: "2h 30m" },
      { id: "m6", title: "Trees & Graphs", type: "lecture", files: 14, duration: "3h 15m" },
      { id: "m7", title: "Dynamic Programming", type: "lecture", files: 18, duration: "5h 00m" },
      { id: "m8", title: "Sorting & Searching", type: "lecture", files: 9, duration: "2h 00m" },
    ],
    coverGradient: "from-secondary-container to-secondary",
    updatedDaysAgo: 3,
    language: "Python",
  },
  {
    id: "r3",
    title: "Abstract Algebra: Groups & Rings",
    slug: "abstract-algebra-groups-rings",
    description: "Rigorous yet accessible treatment of group theory, ring theory, and field extensions. Includes intuitive visualizations and 150+ proofs.",
    courseCode: "MATH 401",
    university: "Universidad Nacional",
    department: "Mathematics",
    semester: "Spring 2025",
    owner: MOCK_USERS[2],
    contributors: [MOCK_USERS[0]],
    tags: ["algebra", "mathematics", "group-theory", "proofs"],
    stars: 784,
    forks: 123,
    discussions: 45,
    views: 8900,
    lastUpdated: "2025-05-18",
    isPublic: true,
    isVerified: false,
    readme: "# Abstract Algebra\n\nBeauty in abstraction...",
    modules: [
      { id: "m9", title: "Group Theory Fundamentals", type: "lecture", files: 11, duration: "3h 00m" },
      { id: "m10", title: "Ring Theory", type: "lecture", files: 9, duration: "2h 30m" },
      { id: "m11", title: "Field Extensions", type: "lecture", files: 7, duration: "2h 00m" },
    ],
    coverGradient: "from-tertiary-container to-tertiary",
    updatedDaysAgo: 7,
    language: "Markdown",
  },
  {
    id: "r4",
    title: "Molecular Biology & Genomics",
    slug: "molecular-biology-genomics",
    description: "Modern molecular biology including DNA replication, transcription, translation, CRISPR, and next-gen sequencing. Lab protocols included.",
    courseCode: "BIO 312",
    university: "University of Cambridge",
    department: "Biology",
    semester: "Fall 2024",
    owner: MOCK_USERS[3],
    contributors: [],
    tags: ["biology", "genomics", "CRISPR", "molecular"],
    stars: 456,
    forks: 78,
    discussions: 31,
    views: 6700,
    lastUpdated: "2025-05-10",
    isPublic: true,
    isVerified: false,
    readme: "# Molecular Biology & Genomics\n\nThe code of life...",
    modules: [
      { id: "m12", title: "DNA Structure & Replication", type: "lecture", files: 8, duration: "2h 20m" },
      { id: "m13", title: "CRISPR & Gene Editing", type: "lecture", files: 12, duration: "3h 30m" },
    ],
    coverGradient: "from-primary-fixed to-surface-tint",
    updatedDaysAgo: 15,
    language: "PDF",
  },
  {
    id: "r5",
    title: "Machine Learning Foundations",
    slug: "machine-learning-foundations",
    description: "Comprehensive ML course from linear regression to neural networks. Includes Jupyter notebooks, datasets, and projects.",
    courseCode: "CS 229",
    university: "MIT",
    department: "Computer Science",
    semester: "Fall 2024",
    owner: MOCK_USERS[1],
    contributors: [MOCK_USERS[0], MOCK_USERS[2], MOCK_USERS[3]],
    tags: ["machine-learning", "python", "neural-networks", "AI"],
    stars: 3891,
    forks: 1204,
    discussions: 412,
    views: 98000,
    lastUpdated: "2025-05-23",
    isPublic: true,
    isVerified: true,
    readme: "# Machine Learning Foundations\n\nFrom zero to production ML...",
    modules: [
      { id: "m14", title: "Supervised Learning", type: "lecture", files: 16, duration: "4h 00m" },
      { id: "m15", title: "Neural Networks", type: "lecture", files: 20, duration: "6h 15m" },
      { id: "m16", title: "Projects & Implementations", type: "assignment", files: 8, duration: null },
    ],
    coverGradient: "from-secondary to-secondary-container",
    updatedDaysAgo: 2,
    language: "Jupyter",
  },
  {
    id: "r6",
    title: "Organic Chemistry I & II",
    slug: "organic-chemistry-i-ii",
    description: "Full two-semester organic chemistry with reaction mechanisms, stereochemistry, and spectroscopy. 300+ reaction cards and mnemonics.",
    courseCode: "CHEM 215",
    university: "University of Lagos",
    department: "Chemistry",
    semester: "Spring 2025",
    owner: MOCK_USERS[0],
    contributors: [MOCK_USERS[2]],
    tags: ["chemistry", "organic", "reactions", "mechanisms"],
    stars: 621,
    forks: 95,
    discussions: 67,
    views: 12300,
    lastUpdated: "2025-05-15",
    isPublic: true,
    isVerified: false,
    readme: "# Organic Chemistry\n\nMastering carbon chemistry...",
    modules: [
      { id: "m17", title: "Nomenclature & Bonding", type: "lecture", files: 10, duration: "2h 45m" },
      { id: "m18", title: "Reaction Mechanisms", type: "lecture", files: 22, duration: "5h 30m" },
      { id: "m19", title: "Flash Cards (300+)", type: "flashcard", files: 1, duration: null },
    ],
    coverGradient: "from-tertiary-fixed to-outline",
    updatedDaysAgo: 10,
    language: "PDF",
  },
];

export const TRENDING_TAGS = [
  "quantum-physics", "algorithms", "machine-learning", "calculus", "linear-algebra",
  "organic-chemistry", "data-structures", "molecular-biology", "statistics", "thermodynamics",
  "computer-architecture", "differential-equations", "neuroscience", "economics", "circuit-theory",
];

export const UNIVERSITIES = [
  { name: "MIT", count: 124, country: "USA" },
  { name: "University of Lagos", count: 89, country: "Nigeria" },
  { name: "Universidad Nacional", count: 67, country: "Colombia" },
  { name: "University of Cambridge", count: 203, country: "UK" },
  { name: "ETH Zurich", count: 145, country: "Switzerland" },
  { name: "University of Cape Town", count: 78, country: "South Africa" },
];

export const STATS = [
  { label: "Repositories", value: "48,291", suffix: "+" },
  { label: "Contributors", value: "312,847", suffix: "+" },
  { label: "Universities", value: "1,203", suffix: "" },
  { label: "Study Hours Saved", value: "4.2M", suffix: "+" },
];

export const TESTIMONIALS = [
  {
    id: "t1",
    quote: "Mantra completely changed how our department shares materials. Lecture notes evolved by 40 students each semester — it's incredible to watch knowledge compound.",
    author: "Prof. Adebayo Williams",
    role: "Head of Computer Science, University of Ibadan",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=adebayo",
  },
  {
    id: "t2",
    quote: "I struggled with abstract algebra for months. Found a Mantra repository with 3 years of improvements by past students. Passed my exams with distinction.",
    author: "Priya Nair",
    role: "Mathematics Student, IIT Bombay",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya",
  },
  {
    id: "t3",
    quote: "The version control philosophy for academic content is genius. You can actually see how understanding of a topic deepened over 5 semesters.",
    author: "Dr. Emeka Uzor",
    role: "Research Fellow, University of Oxford",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=emeka",
  },
];

export function formatNumber(n: number): string {
  if (n >= 1000000) return (n / 1000000).toFixed(1) + "M";
  if (n >= 1000) return (n / 1000).toFixed(1) + "k";
  return n.toString();
}

export function timeAgo(daysAgo: number): string {
  if (daysAgo === 0) return "today";
  if (daysAgo === 1) return "yesterday";
  if (daysAgo < 7) return `${daysAgo} days ago`;
  if (daysAgo < 30) return `${Math.floor(daysAgo / 7)} weeks ago`;
  return `${Math.floor(daysAgo / 30)} months ago`;
}
