import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#fef9f2",
        "surface-dim": "#ded9d3",
        "surface-bright": "#fef9f2",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f8f3ec",
        "surface-container": "#f2ede6",
        "surface-container-high": "#ece7e1",
        "surface-container-highest": "#e7e2db",
        "on-surface": "#1d1b17",
        "on-surface-variant": "#4d453f",
        "inverse-surface": "#32302c",
        "inverse-on-surface": "#f5f0e9",
        "outline": "#7f756e",
        "outline-variant": "#d0c4bc",
        "surface-tint": "#695c51",
        "primary": "#140b05",
        "on-primary": "#ffffff",
        "primary-container": "#2b2118",
        "on-primary-container": "#97877b",
        "inverse-primary": "#d5c3b5",
        "secondary": "#735b25",
        "on-secondary": "#ffffff",
        "secondary-container": "#fedb99",
        "on-secondary-container": "#785f29",
        "tertiary": "#120b04",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#2a2118",
        "on-tertiary-container": "#95887b",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#f2dfd1",
        "primary-fixed-dim": "#d5c3b5",
        "on-primary-fixed": "#231a11",
        "on-primary-fixed-variant": "#51443a",
        "secondary-fixed": "#ffdea0",
        "secondary-fixed-dim": "#e3c282",
        "on-secondary-fixed": "#261a00",
        "on-secondary-fixed-variant": "#5a430f",
        "tertiary-fixed": "#f0e0d1",
        "tertiary-fixed-dim": "#d4c4b5",
        "on-tertiary-fixed": "#221a11",
        "on-tertiary-fixed-variant": "#50453a",
        "background": "#fef9f2",
        "on-background": "#1d1b17",
        "surface-variant": "#e7e2db",
      },
      fontFamily: {
        "manrope": ["Manrope", "sans-serif"],
        "vietnam": ["Be Vietnam Pro", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-md": ["36px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "2xl": "2rem",
        "3xl": "2.5rem",
        "full": "9999px",
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "40px",
        "xxl": "64px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "container-max": "1200px",
      },
      boxShadow: {
        "card": "0px 10px 30px rgba(43,33,24,0.04)",
        "card-hover": "0px 15px 40px rgba(43,33,24,0.08)",
        "modal": "0px 24px 64px rgba(43,33,24,0.12)",
        "glow": "0 0 24px rgba(115, 91, 37, 0.15)",
      },
      animation: {
        "float": "float 6s ease-in-out infinite",
        "pulse-slow": "pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "fade-in": "fadeIn 0.5s ease-out",
        "slide-up": "slideUp 0.5s ease-out",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-12px)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      backdropBlur: {
        "xs": "2px",
      },
    },
  },
  plugins: [],
};

export default config;
